### ISSUE TITLE
Right click doesn't perfom at the right spot on unactives windows

### ISSUE THREAD

**Issue by CLSixteen** [Yokani/DofusHeroes#1]
After setting all up, everything works fine excepts for the right click feature. 

The position of the right click on unactives windows isn't the same as the active one. Is there any fix for that or am I misusing the feature?

**Comment by CLSixteen** [comment]
I'd a look on your code and don't really understand why this bug is happening. I think this is Dofus dependant and can't really do anything to fix it.

**Comment by Yokani** [comment]
Hi!

Thanks for trying it out!
Yes this is dofus dependant and sadly i have no fix for it yet. Might as well remove the feature for the time being~
